apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: echo-port
      protocol: TCP
  selector:
    app: echoserver-app